JAMSv1.0/Models/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JAMSv1._0.Models
{
    public class Question
    {
        public int QuestionID { get; set; }

        public int? JobId { get; set; }

        [Display(Name = "Question")]
        [Required]
        public string QuestionString { get; set; }
        [Display(Name = "Answer 1")]
        [Required]
        public string Answer1 { get; set; }
        [Display(Name = "Answer 2")]
        [Required]
        public string Answer2 { get; set; }
        [Display(Name = "Answer 3")]
        [Required]
        public string Answer3 { get; set; }
        [Display(Name = "Answer 4")]
        [Required]
        public string Answer4 { get; set; }
        [Display(Name = "Correct Answer")]
        [Required]
        public string CorrectAnswer { get; set; }

        [Display(Name = "Selected Answer")]
        public string SelectedAnswer { get; set; }
    }
}

JAMSv1.0/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using JAMSv1._0.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace JAMSv1._0.Controllers
{
    /// <summary>
    /// Controller for questions and quiz functionality
    /// </summary>
    public class QuestionsController : ApplicationController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        /// <summary>
        /// GET: Questions/Index
        /// </summary>
        /// <returns>View of index with quiz questions</returns>
        public ActionResult Index()
        {
            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var currentUser = manager.FindById(User.Identity.GetUserId());
            currentUser.AccomplishmentComplete = true;
            manager.UpdateAsync(currentUser);

            Quiz newQuiz = new Quiz();
            Random rand = new Random();
            List<Question> questionList = new List<Question>(db.Questions.ToList().Count);
            foreach (var item in db.Questions.ToList())
            {
                questionList.Add(item);
            }
            int counter = 0;

            do
            {
                var index = rand.Next() % questionList.Count;
                var k = questionList[index];
                

                foreach (var question in db.Questions.ToList())
                {
                    if (question == k && question.JobId == currentUser.JobId)
                    {
                        newQuiz.Questions.Add(question);
                        counter++;
                    }
                }
                questionList.RemoveAt(index);
                
                
            } while (counter < 5);
                
            
            return View(newQuiz);
        }

        /// <summary>
        /// POST: Questions/Index
        /// </summary>
        /// <param name="model">Quiz model</param>
        /// <param name="File">Resume file</param>
        /// <returns>Thank you page</returns>
        [HttpPost]
        public ActionResult Index(Quiz model)
        {
            if (ModelState.IsValid)
            {
                foreach (Question q in model.Questions)
                {
                    if (q.SelectedAnswer == q.CorrectAnswer)
                    {
                        model.rightAnswers++;
                    }
                }
                var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                var currentUser = manager.FindById(User.Identity.GetUserId());
                currentUser.PrescreeningComplete = true;
                manager.UpdateAsync(currentUser);

                Job newJob = new Job();

                foreach (var job in db.Jobs.ToList())
                {
                    if (job.JobId == currentUser.JobId)
                    {
                        newJob = job;
                    }
                }

                SendEmail(model, newJob);
                currentUser.ApplicationComplete = true;
                return RedirectToAction("ThankYou");
            }
            
            return View(model);
        }

        /// <summary>
        /// GET: Questions/Details
        /// </summary>
        /// <param name="id">Question id</param>
        /// <returns>Question detail</returns>
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            Job job = db.Jobs.Find(question.JobId);
            //ViewBag.tempJobName = job.JobName;
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        /// <summary>
        /// GET: Questions/Create
        /// </summary>
        /// <returns>Create view</returns>
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.JobId = new SelectList(db.Jobs, "JobId", "JobName");
            return View();
        }

        /// <summary>
        /// POST: Questions/Create
        /// </summary>
        /// <param name="question">Question</param>
        /// <returns>View of index</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(
            [Bind(Include = "QuestionID,QuestionString,Answer1,Answer2,Answer3,Answer4,CorrectAnswer,JobId")] Question
                question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("ListAllQuestions");
            }

            return View(question);
        }

        /// <summary>
        /// GET: Questions/Edit
        /// </summary>
        /// <param name="id">Question id</param>
        /// <returns>View of edit questions</returns>
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.JobId = new SelectList(db.Jobs, "JobId", "JobName");
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        /// <summary>
        /// POST: Questions/Edit
        /// </summary>
        /// <param name="question">Question id</param>
        /// <returns>View of question index</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(
            [Bind(Include = "QuestionID,QuestionString,Answer1,Answer2,Answer3,Answer4,CorrectAnswer,JobId")] Question
                question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListAllQuestions");
            }
            return View(question);
        }

        /// <summary>
        /// GET: Questions/Delete
        /// </summary>
        /// <param name="id">Question id</param>
        /// <returns>View of question delete</returns>
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        /// <summary>
        /// POST: Questions/Delete
        /// </summary>
        /// <param name="id">Question id</param>
        /// <returns>View of quesstions index</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("ListAllQuestions");
        }
        /// <summary>
        /// GET: Questions/Dispose
        /// </summary>
        /// <param name="disposing">bool</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        /// <summary>
        /// GET: Questions/ThankYou
        /// </summary>
        /// <returns>View of questions thankyou</returns>
        public ActionResult ThankYou(Quiz model)
        {
            if (ModelState.IsValid)
            {
                foreach (Question q in model.Questions)
                {
                    if (q.SelectedAnswer == q.CorrectAnswer)
                    {
                        model.rightAnswers++;
                    }
                }
                var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                var currentUser = manager.FindById(User.Identity.GetUserId());
                Job newJob = new Job();

                foreach (var job in db.Jobs.ToList())
                {
                    if (job.JobId == currentUser.JobId)
                    {
                        newJob = job;
                    }
                }
                if (currentUser.ApplicationComplete != true)
                {
                    SendEmail(model, newJob);
                }
                
                // Here is some code to uncomment in order to reset the workflow and start from the beginning

                currentUser.ApplyComplete = false;
                currentUser.UploadComplete = false;
                currentUser.AccomplishmentComplete = false;
                currentUser.PrescreeningComplete = false;
                currentUser.ResumeFilePath = null;
                manager.UpdateAsync(currentUser);
                
                return View("ThankYou");
            }
            return View("ThankYou");
        }

        /// <summary>
        /// GET: Questions/ListAllQuestions
        /// </summary>
        /// <returns>View of all questions</returns>
        [Authorize(Roles = "Admin")]
        public ActionResult ListAllQuestions()
        {

JAMSv1.0/Views/Questions/Create.cshtml
@model JAMSv1._0.Models.Question

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.QuestionString, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuestionString, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuestionString, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CorrectAnswer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CorrectAnswer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CorrectAnswer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobId, "Job Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.JobId, ViewBag.JobId as SelectList, "Please Select a Job Category", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.JobId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListAllQuestions")
</div>

JAMSv1.0/Views/Questions/Delete.cshtml
@model JAMSv1._0.Models.Question

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.QuestionString)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuestionString)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CorrectAnswer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CorrectAnswer)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ListAllQuestions")
        </div>
    }
</div>

JAMSv1.0/Views/Questions/Details.cshtml
@model JAMSv1._0.Models.Question

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.QuestionString)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuestionString)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CorrectAnswer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CorrectAnswer)
        </dd>
        <dt>
            @Html.LabelFor(model => model.JobId, "Job Name")
        </dt>

        <dd>
            @ViewBag.tempJobName
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.QuestionID }) |
    @Html.ActionLink("Back to List", "ListAllQuestions")
</p>

JAMSv1.0/Views/Questions/Edit.cshtml
@model JAMSv1._0.Models.Question

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.QuestionID)

        <div class="form-group">
            @Html.LabelFor(model => model.QuestionString, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuestionString, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuestionString, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CorrectAnswer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CorrectAnswer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CorrectAnswer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobId, "Job Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.JobId, ViewBag.JobId as SelectList, "Job Category", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.JobId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListAllQuestions")
</div>

JAMSv1.0/Views/Questions/Index.cshtml
@model JAMSv1._0.Models.Quiz
@{
    ViewBag.Title = "Index";
}

<div id="progressbar">
    <div id="progressbar" class="all-rounded" style="width: 80%"><span></span></div>
</div>

<meta http-equiv="refresh" content="1800; URL=/Questions/ThankYou">

<div class="row">
    <div class="col-md-offset-1">
        <section id="questionForm">
            <h2>Questions</h2>

            <div class="timer">
                <form action="ThankYou" name="counter">
                    <input type="text" size="8"
                           name="d2">
                </form>
            </div>

            <div style="width:1024px; margin:auto">
                <script type="text/javascript">
                    var minutes = 30
                    var seconds = 00
                    function SubmitForm() {
                        $('#THANKYOU').submit();
                    }

                    document.counter.d2.value = '30:00'

                    function display() {
                        if (seconds <= 0) {
                            minutes -= 1
                            seconds += 59
                        }
                        if (minutes <= -1) {

                            $("form").trigger("submit");

                        }
                        else
                            seconds -= 1
                        document.counter.d2.value = minutes + ":" + seconds
                        setTimeout("display()", 1000)
                    }
                    display()
                </script>
            </div>

            
            
            @using (Html.BeginForm("Index", "Questions", FormMethod.Post, new { ID = "THANKYOU" }))
            {
                @Html.EditorFor(x => x.Questions)

                <input type="submit" id="submit" class="btn btn-default" value="Submit" />
            }
        </section>
    </div>
</div>

JAMSv1.0/Views/Questions/ListAllQuestions.cshtml
@model IEnumerable<JAMSv1._0.Models.Question>
@{
    ViewBag.Title = "ListAllQuestions";
}
@Html.ActionLink("Back To Admin Page", "../Roles/Index") | @Html.ActionLink("Create New Question", "Create")
<h2>List All Questions</h2>
<table class="table">
    @foreach (var item in Model)
    {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.QuestionString)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.QuestionID }) |
                @Html.ActionLink("Details", "Details", new { id = item.QuestionID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.QuestionID })
            </td>
        </tr>
    }
    </table>

JAMSv1.0/Views/Questions/ThankYou.cshtml
@model JAMSv1._0.Models.Question
@{
    ViewBag.Title = "ThankYou";
}

<div id="progressbarone">
    <div id="progressbarone" class="all-rounded" style="width: 100%"><span></span></div>
</div>

<div class="thankyou">
    <h2>Thank you for applying!</h2>
</div>
<p>&nbsp; &nbsp; &nbsp; &nbsp;</p>

<div class="thankyou2">
    <p>What can we achieve together? Technology has redefined what’s possible in business. At Sogeti, our goal is to redefine what’s possible from a technology partner:</p>
    <ul>
        <li><b>Honesty</b> — reflecting personal and business integrity, a sense of honor, respect for commitments and fairness in all contract pursuits and negotiations</li>
        <li><b>Boldness</b> — a willingness to take risks, enthusiasm for new undertakings, questioning of what currently exists, enjoyment of competition and entrepreneurial audacity tempered by experience and wisdom</li>
        <li><b>Trust</b> — designating responsibility to people and teams, shared decision-making, total openness and the free flow of information and ideas within our company</li>
        <li><b>Freedom</b> — fostering independence of mind, judgment and action, the spirit of initiative and creativity, tolerance and respect for others who are different</li>
        <li><b>Team Spirit</b> — solidarity, loyalty, camaraderie, and the willingness to share in our collective success</li>
        <li><b>Modesty</b> — discretion, spontaneity, and openness in relationships</li>
        <li><b>Fun</b> — achieving pride in our work while constantly striving for quality</li>
    </ul>  
</div>

<p>&nbsp; &nbsp; &nbsp; &nbsp;</p>

<div class="thankyou">
    <h2>Learn more about Sogeti <a href="https://US.sogeti.com">here</a> </h2>
</div>

<p>&nbsp; &nbsp; &nbsp; &nbsp;</p>


<div class="sogetivideo">
    <embed width="640" height="385"
           src="http://www.youtube.com/v/jjQCNMnv4a0"
           type="application/x-shockwave-flash">
</div>
