JAMSv1.0/Controllers/AccomplishmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JAMSv1._0.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace JAMSv1._0.Controllers
{
    /// <summary>
    /// Controller for Accomplishments with CRUD functionality
    /// </summary>
    public class AccomplishmentsController : ApplicationController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        /// <summary>
        /// GET: Accomplishments/Index
        /// </summary>
        /// <returns>View list of accomplishments</returns>
        public ActionResult Index(Accomplishment accompish)
        {
            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var currentUser = manager.FindById(User.Identity.GetUserId());
            if(ModelState.IsValid)
            {
                return View(accompish);
            }
            return View(currentUser.Accomplishment);
            //return View(db.Accomplishments.ToList());
        }

        /// <summary>
        /// GET: Accomplishments/Details
        /// </summary>
        /// <param name="id">Accomplishment ID</param>
        /// <returns>Accomplishment Details</returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Accomplishment accomplishment = db.Accomplishments.Find(id);
            if (accomplishment == null)
            {
                return HttpNotFound();
            }
            return View(accomplishment);
        }

        /// <summary>
        /// GET: Accomplishments/Create
        /// </summary>
        /// <returns>Create view</returns>
        public ActionResult Create()
        {
            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var currentUser = manager.FindById(User.Identity.GetUserId());
            return View(currentUser.Accomplishment);
        }

        /// <summary>
        /// POST: Accomplishments/Create
        /// </summary>
        /// <param name="accomplishment">Stores user input</param>
        /// <returns>View to Index</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AccomplishmentID,AccomplishmentDate1,Accomplishment1,AccomplishmentDate2,Accomplishment2,AccomplishmentDate3,Accomplishment3")] Accomplishment accomplishment)
        {
            if (ModelState.IsValid)
            {
                db.Accomplishments.Add(accomplishment);
                db.SaveChanges();
                var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                var currentUser = manager.FindById(User.Identity.GetUserId());
                currentUser.Accomplishment = accomplishment;
                manager.UpdateAsync(currentUser);
                return RedirectToAction("Index", currentUser.Accomplishment);
            }

            return View(accomplishment);
        }

        /// <summary>
        /// GET: Accomplishments/Edit/
        /// </summary>
        /// <param name="id">Accomplishment Id</param>
        /// <returns>Details of the Accomplishment</returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Accomplishment accomplishment = db.Accomplishments.Find(id);
            if (accomplishment == null)
            {
                return HttpNotFound();
            }
            return View(accomplishment);
        }

        /// <summary>
        /// POST: Accomplishments/Edit/
        /// </summary>
        /// <param name="accomplishment">User Input</param>
        /// <returns>View to Index</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AccomplishmentID,AccomplishmentDate1,Accomplishment1,AccomplishmentDate2,Accomplishment2,AccomplishmentDate3,Accomplishment3")] Accomplishment accomplishment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(accomplishment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(accomplishment);
        }

        /// <summary>
        /// GET: Accomplishments/Delete/
        /// </summary>
        /// <param name="id">Accomplishment Id</param>
        /// <returns>Accomplishment Index</returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Accomplishment accomplishment = db.Accomplishments.Find(id);
            if (accomplishment == null)
            {
                return HttpNotFound();
            }
            return View(accomplishment);
        }

        /// <summary>
        /// POST: Accomplishments/Delete
        /// </summary>
        /// <param name="id">Accomplishment Id</param>
        /// <returns>View to Index</returns>
 
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Accomplishment accomplishment = db.Accomplishments.Find(id);
            db.Accomplishments.Remove(accomplishment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        /// <summary>
        /// Dispose of Accomplishment
        /// </summary>
        /// <param name="disposing">Accomplishment to Dispose</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JAMSv1.0/Controllers/HomeController.cs
using System;
using System.IO;
using System.Web.Mvc;
using JAMSv1._0.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;

namespace JAMSv1._0.Controllers
{
    /// <summary>
    /// Controller that holds home page functionality
    /// </summary>
    public class HomeController : ApplicationController
    {
        /// <summary>
        /// GET: /Home/Register
        /// </summary>
        /// <returns>View of index</returns>
        public ActionResult Index()
        {
            return View(); 
        }

        /// <summary>
        /// GET: /Home/Upload
        /// </summary>
        /// <returns>View of upload</returns>
        public ActionResult Upload(int? jobId)
        {
            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var currentUser = manager.FindById(User.Identity.GetUserId());
            currentUser.ApplyComplete = true;
            manager.UpdateAsync(currentUser);
            currentUser.JobId = Convert.ToInt32(jobId);
            if (currentUser.JobId == 0)
            {
                currentUser.JobId = 999;
            }
            return View();
        }

        /// <summary>
        /// POST: /Home/Upload
        /// </summary>
        /// <param name="resume">Resume</param>
        /// <param name="command">string</param>
        /// <returns>Resume added and continue</returns>
        [HttpPost]
        [Authorize]
        public ActionResult Upload(Resume resume, string command)
        {
            //This block of code does nothing. I left it here just in case somebody else was using it.
            //if (command == "Next")
            //{
            //    RedirectToAction("Create", "Accomplishments");
            //}
            try
            {
                if (resume.File.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(resume.File.FileName);
                    string path = Path.Combine(Server.MapPath("~/Content/Resumes"), fileName);
                    StoreResumeFilePath(path);
                    resume.File.SaveAs(path);
                    var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                    var currentUser = manager.FindById(User.Identity.GetUserId());
                    currentUser.ResumeFilePath = path;
                    currentUser.UploadComplete = true;
                    manager.UpdateAsync(currentUser);
                }
                TempData["notice"] = "Resume Added:  "+ resume.File.FileName;
                return View(resume);
            }
            catch (Exception)
            {
                ViewBag.Message = "Upload Error";
                return View("Upload");
            }
        }

        /// <summary>
        /// Contact page (unused)
        /// </summary>
        /// <returns>View of contact</returns>
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

JAMSv1.0/Views/Home/Contact.cshtml
@*@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>*@

JAMSv1.0/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="entry-summary">

    <p><img class="Working" alt="Working-at-Sogeti" src="~/Working-at-Sogeti-header.jpg" width="1100" height="275" /><br /></p>

</div>
<div class="col-md-offset-1">
    <p>The IT industry is exciting, fast paced and highly rewarding. That&#8217;s also how people describe their careers at Sogeti.</p>

    @*<p>&nbsp;</p>*@
    <p>At Sogeti, we pride ourselves on hiring the best and brightest talent across the country. We realize our team is our greatest strength, and as such we know making Sogeti a great place to work is a top priority.</p>
    @*<p>&nbsp;</p>*@
    <p>We are dedicated to the success of each person and committed to providing:</p>
    <ul>
        <li>An exciting, rewarding, and fun work environment.</li>
        <li>Top training and educational programs to help you reach your professional goals.</li>
        <li>Opportunities for continued growth and advancement.</li>
        <li>A highly competitive compensation package.</li>
        <li>A fun, team based approach—ensuring support is always available.</li>
    </ul>
    @*<p>&nbsp;</p>*@
    <p>Ready to join our team?  @Html.ActionLink("Register", "../Account/Register")&nbsp;&nbsp;@*And then upload your Resume.&nbsp;&nbsp;@Html.ActionLink("Upload", "Upload")</p>*@
    <p>Already Registered?  @Html.ActionLink("Login", "../Account/Login")</p>
    <p>@*<input type="submit" class="btn btn-default" id="Login" value="Login" />*@</p><!-- .entry-summary -->
</div>

JAMSv1.0/Views/Home/Upload.cshtml
@{
    ViewBag.Title = "Upload";
}

<div id="progressbar">
    <div id="progressbar" class="all-rounded" style="width: 20%"><span></span></div>
</div>

<div class="jumbotron">

    <h2>Job Application Management System</h2>
    <p class="lead2"> Welcome @((string)(ViewData["FullName"])), Please upload your resume here. Thank you!</p>
    @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <table>
            <tr>
                <td> <label> &nbsp; </label> <input type="file" class="btn btn-default" name="File" id="File" /></td>
            </tr>
            <tr>
                <td><input type="submit" class="btn btn-default" id="upload" value="Upload" /></td>
            </tr>
        </table>
        if (TempData["notice"] != null)
        {
            <p>@TempData["notice"]</p>
            <p><button class="btn btn-default" onclick="location.href='@Url.Action("Create", "Accomplishments")';return false;">Continue To Accomplishments</button></p>
        }
    }
</div>